"""Type stub generator for Monty's type checker."""

import re

from grail._types import ExternalSpec, InputSpec


def _needs_any_import(type_str: str) -> bool:
    """Check if a type annotation string references typing.Any."""
    return bool(re.search(r"\bAny\b", type_str))


def generate_stubs(
    externals: dict[str, ExternalSpec],
    inputs: dict[str, InputSpec],
) -> str:
    """
    Generate .pyi stub file content from declarations.

    Args:
        externals: External function specifications.
        inputs: Input variable specifications.

    Returns:
        .pyi file content as string.
    """

    lines = ["# Auto-generated by grail — do not edit", ""]

    needs_any = False

    for external in externals.values():
        if _needs_any_import(external.return_type):
            needs_any = True
        for param in external.parameters:
            if _needs_any_import(param.type_annotation):
                needs_any = True

    for input_spec in inputs.values():
        if _needs_any_import(input_spec.type_annotation):
            needs_any = True

    if needs_any:
        lines.append("from typing import Any")
        lines.append("")

    if inputs:
        for input_spec in inputs.values():
            lines.append(f"{input_spec.name}: {input_spec.type_annotation}")
        lines.append("")

    for external in externals.values():
        params = []
        for param in external.parameters:
            if param.default is not None:
                if isinstance(param.default, str):
                    params.append(f"{param.name}: {param.type_annotation} = {param.default}")
                else:
                    params.append(f"{param.name}: {param.type_annotation} = {repr(param.default)}")
            else:
                params.append(f"{param.name}: {param.type_annotation}")

        params_str = ", ".join(params)

        if external.is_async:
            lines.append(f"async def {external.name}({params_str}) -> {external.return_type}:")
        else:
            lines.append(f"def {external.name}({params_str}) -> {external.return_type}:")

        if external.docstring:
            lines.append(f'    """{external.docstring}"""')

        lines.append("    ...")
        lines.append("")

    return "\n".join(lines)
