# Auto-generated by grail — this is what Monty actually executes

from typing import Any
team_data = await get_team_members(department=department)
members = team_data.get('members', [])
over_budget = []
for member in members:
    uid = member['id']
    expenses = await get_expenses(user_id=uid)
    items = expenses.get('items', [])
    total = sum((item['amount'] for item in items))
    if total > budget_limit:
        custom = await get_custom_budget(user_id=uid)
        if custom is None or total > custom.get('limit', budget_limit):
            over_budget.append({'user_id': uid, 'name': member['name'], 'total': total, 'over_by': total - budget_limit})
{'analyzed': len(members), 'over_budget_count': len(over_budget), 'details': over_budget}