# Auto-generated by grail — do not edit

from typing import Any

budget_limit: float
department: str

async def get_team_members(department: str) -> dict[str, Any]:
    """Get list of team members for a department."""
    ...

async def get_expenses(user_id: int) -> dict[str, Any]:
    """Get expense line items for a user."""
    ...

async def get_custom_budget(user_id: int) -> dict[str, Any] | None:
    """Get custom budget for a user if they have one."""
    ...
