# Auto-generated by grail — this is what Monty actually executes

if len(text) <= max_length:
    result = {'truncated': False, 'text': text, 'original_length': len(text)}
else:
    result = {'truncated': True, 'text': text[:max_length] + '...', 'original_length': len(text), 'truncated_to': max_length}
result