# Auto-generated by grail — this is what Monty actually executes

try:
    entries = ['README.md', 'src', 'agents', 'tests']
    hidden_entries = ['.gitignore', '.env.example']
    result = {'entries': hidden_entries + entries if show_all else entries, 'show_hidden': bool(show_all)}
except Exception as exc:
    result = {'error': str(exc)}
result